from django.core.management.base import BaseCommand
from esim_store.models import Country

class Command(BaseCommand):
    help = 'Add missing countries to the database'

    def handle(self, *args, **options):
        # List of all countries with their ISO codes
        countries_data = [
            ('Afghanistan', 'AF'),
            ('Albania', 'AL'),
            ('Algeria', 'DZ'),
            ('Andorra', 'AD'),
            ('Angola', 'AO'),
            ('Antigua and Barbuda', 'AG'),
            ('Argentina', 'AR'),
            ('Armenia', 'AM'),
            ('Austria', 'AT'),
            ('Azerbaijan', 'AZ'),
            ('Bahamas', 'BS'),
            ('Bahrain', 'BH'),
            ('Bangladesh', 'BD'),
            ('Barbados', 'BB'),
            ('Belarus', 'BY'),
            ('Belgium', 'BE'),
            ('Belize', 'BZ'),
            ('Benin', 'BJ'),
            ('Bhutan', 'BT'),
            ('Bolivia', 'BO'),
            ('Bosnia and Herzegovina', 'BA'),
            ('Botswana', 'BW'),
            ('Brazil', 'BR'),
            ('Brunei', 'BN'),
            ('Bulgaria', 'BG'),
            ('Burkina Faso', 'BF'),
            ('Burundi', 'BI'),
            ('Cabo Verde', 'CV'),
            ('Cambodia', 'KH'),
            ('Cameroon', 'CM'),
            ('Central African Republic', 'CF'),
            ('Chad', 'TD'),
            ('Chile', 'CL'),
            ('China', 'CN'),
            ('Colombia', 'CO'),
            ('Comoros', 'KM'),
            ('Congo, Democratic Republic of the', 'CD'),
            ('Congo, Republic of the', 'CG'),
            ('Costa Rica', 'CR'),
            ('Croatia', 'HR'),
            ('Cuba', 'CU'),
            ('Cyprus', 'CY'),
            ('Czech Republic', 'CZ'),
            ('Denmark', 'DK'),
            ('Djibouti', 'DJ'),
            ('Dominica', 'DM'),
            ('Dominican Republic', 'DO'),
            ('Ecuador', 'EC'),
            ('Egypt', 'EG'),
            ('El Salvador', 'SV'),
            ('Equatorial Guinea', 'GQ'),
            ('Eritrea', 'ER'),
            ('Estonia', 'EE'),
            ('Eswatini', 'SZ'),
            ('Ethiopia', 'ET'),
            ('Fiji', 'FJ'),
            ('Finland', 'FI'),
            ('Gabon', 'GA'),
            ('Gambia', 'GM'),
            ('Georgia', 'GE'),
            ('Ghana', 'GH'),
            ('Greece', 'GR'),
            ('Grenada', 'GD'),
            ('Guatemala', 'GT'),
            ('Guinea', 'GN'),
            ('Guinea-Bissau', 'GW'),
            ('Guyana', 'GY'),
            ('Haiti', 'HT'),
            ('Honduras', 'HN'),
            ('Hungary', 'HU'),
            ('Iceland', 'IS'),
            ('India', 'IN'),
            ('Indonesia', 'ID'),
            ('Iran', 'IR'),
            ('Iraq', 'IQ'),
            ('Ireland', 'IE'),
            ('Israel', 'IL'),
            ('Jamaica', 'JM'),
            ('Jordan', 'JO'),
            ('Kazakhstan', 'KZ'),
            ('Kenya', 'KE'),
            ('Kiribati', 'KI'),
            ('Korea, North', 'KP'),
            ('Korea, South', 'KR'),
            ('Kosovo', 'XK'),
            ('Kuwait', 'KW'),
            ('Kyrgyzstan', 'KG'),
            ('Laos', 'LA'),
            ('Latvia', 'LV'),
            ('Lebanon', 'LB'),
            ('Lesotho', 'LS'),
            ('Liberia', 'LR'),
            ('Libya', 'LY'),
            ('Liechtenstein', 'LI'),
            ('Lithuania', 'LT'),
            ('Luxembourg', 'LU'),
            ('Madagascar', 'MG'),
            ('Malawi', 'MW'),
            ('Malaysia', 'MY'),
            ('Maldives', 'MV'),
            ('Mali', 'ML'),
            ('Malta', 'MT'),
            ('Marshall Islands', 'MH'),
            ('Mauritania', 'MR'),
            ('Mauritius', 'MU'),
            ('Mexico', 'MX'),
            ('Micronesia', 'FM'),
            ('Moldova', 'MD'),
            ('Monaco', 'MC'),
            ('Mongolia', 'MN'),
            ('Montenegro', 'ME'),
            ('Morocco', 'MA'),
            ('Mozambique', 'MZ'),
            ('Myanmar', 'MM'),
            ('Namibia', 'NA'),
            ('Nauru', 'NR'),
            ('Nepal', 'NP'),
            ('Netherlands', 'NL'),
            ('New Zealand', 'NZ'),
            ('Nicaragua', 'NI'),
            ('Niger', 'NE'),
            ('Nigeria', 'NG'),
            ('North Macedonia', 'MK'),
            ('Norway', 'NO'),
            ('Oman', 'OM'),
            ('Pakistan', 'PK'),
            ('Palau', 'PW'),
            ('Panama', 'PA'),
            ('Papua New Guinea', 'PG'),
            ('Paraguay', 'PY'),
            ('Peru', 'PE'),
            ('Philippines', 'PH'),
            ('Poland', 'PL'),
            ('Portugal', 'PT'),
            ('Qatar', 'QA'),
            ('Romania', 'RO'),
            ('Russia', 'RU'),
            ('Rwanda', 'RW'),
            ('Saint Kitts and Nevis', 'KN'),
            ('Saint Lucia', 'LC'),
            ('Saint Vincent and the Grenadines', 'VC'),
            ('Samoa', 'WS'),
            ('San Marino', 'SM'),
            ('Sao Tome and Principe', 'ST'),
            ('Saudi Arabia', 'SA'),
            ('Senegal', 'SN'),
            ('Serbia', 'RS'),
            ('Seychelles', 'SC'),
            ('Sierra Leone', 'SL'),
            ('Slovakia', 'SK'),
            ('Slovenia', 'SI'),
            ('Solomon Islands', 'SB'),
            ('Somalia', 'SO'),
            ('South Africa', 'ZA'),
            ('South Sudan', 'SS'),
            ('Sri Lanka', 'LK'),
            ('Sudan', 'SD'),
            ('Suriname', 'SR'),
            ('Sweden', 'SE'),
            ('Switzerland', 'CH'),
            ('Syria', 'SY'),
            ('Taiwan', 'TW'),
            ('Tajikistan', 'TJ'),
            ('Tanzania', 'TZ'),
            ('Timor-Leste', 'TL'),
            ('Togo', 'TG'),
            ('Tonga', 'TO'),
            ('Trinidad and Tobago', 'TT'),
            ('Tunisia', 'TN'),
            ('Turkey', 'TR'),
            ('Turkmenistan', 'TM'),
            ('Tuvalu', 'TV'),
            ('Uganda', 'UG'),
            ('Ukraine', 'UA'),
            ('United Kingdom', 'GB'),
            ('Uruguay', 'UY'),
            ('Uzbekistan', 'UZ'),
            ('Vanuatu', 'VU'),
            ('Vatican City', 'VA'),
            ('Venezuela', 'VE'),
            ('Vietnam', 'VN'),
            ('Yemen', 'YE'),
            ('Zambia', 'ZM'),
            ('Zimbabwe', 'ZW'),
        ]

        created_count = 0
        skipped_count = 0

        for country_name, country_code in countries_data:
            # Check if country already exists by code
            if not Country.objects.filter(code=country_code).exists():
                # Create new country
                Country.objects.create(code=country_code, name=country_name)
                created_count += 1
                self.stdout.write(f'Created: {country_name} ({country_code})')
            else:
                skipped_count += 1
                self.stdout.write(f'Skipped: {country_name} ({country_code}) - already exists')

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully added {created_count} new countries and skipped {skipped_count} existing countries'
            )
        )